# fly.toml app configuration file generated for free-exchange-rates-api on 2023-08-14T04:44:50+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "free-exchange-rates-api"
primary_region = "cdg"

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  processes = ["app"]
