name: "test"

on:
  pull_request:
    branches: [master]

jobs:
  test:
    name: "Unit tests"
    runs-on: "ubuntu-latest"

    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: npm ci
        run: npm ci

      - name: npm test
        run: npm test
